// BuiltInData — 真实种子数据（从 sindresorhus/awesome README 提取）
// 不依赖网络：保证发布版本离线也能展示真实软件库

export interface BuiltInPackage {
    name: string;
    owner: string;
    repo: string;
    url: string;
    category: string;  // CategoryEngine id
    description: string;
}

export const BUILT_IN_PACKAGES: BuiltInPackage[] = [
    { name: "Node.js", owner: "sindresorhus", repo: "awesome-nodejs", url: "https://github.com/sindresorhus/awesome-nodejs", category: "dev-tools", description: "awesome platforms curated list" },
    { name: "Cross-Platform", owner: "bcoe", repo: "awesome-cross-platform-nodejs", url: "https://github.com/bcoe/awesome-cross-platform-nodejs", category: "dev-tools", description: "awesome platforms curated list" },
    { name: "Frontend Development", owner: "dypsilon", repo: "frontend-dev-bookmarks", url: "https://github.com/dypsilon/frontend-dev-bookmarks", category: "dev-tools", description: "awesome platforms curated list" },
    { name: "iOS", owner: "vsouza", repo: "awesome-ios", url: "https://github.com/vsouza/awesome-ios", category: "dev-tools", description: "awesome platforms curated list" },
    { name: "Android", owner: "JStumpp", repo: "awesome-android", url: "https://github.com/JStumpp/awesome-android", category: "dev-tools", description: "awesome platforms curated list" },
    { name: "JavaScript", owner: "sorrycc", repo: "awesome-javascript", url: "https://github.com/sorrycc/awesome-javascript", category: "dev-tools", description: "awesome programming languages curated list" },
    { name: "Promises", owner: "wbinnssmith", repo: "awesome-promises", url: "https://github.com/wbinnssmith/awesome-promises", category: "dev-tools", description: "awesome programming languages curated list" },
    { name: "Standard Style", owner: "standard", repo: "awesome-standard", url: "https://github.com/standard/awesome-standard", category: "dev-tools", description: "awesome programming languages curated list" },
    { name: "Must Watch Talks", owner: "bolshchikov", repo: "js-must-watch", url: "https://github.com/bolshchikov/js-must-watch", category: "dev-tools", description: "awesome programming languages curated list" },
    { name: "Tips", owner: "loverajoel", repo: "jstips", url: "https://github.com/loverajoel/jstips", category: "dev-tools", description: "awesome programming languages curated list" },
    { name: "ES6 Tools", owner: "addyosmani", repo: "es6-tools", url: "https://github.com/addyosmani/es6-tools", category: "web", description: "awesome front-end development curated list" },
    { name: "Web Performance Optimization", owner: "davidsonfellipe", repo: "awesome-wpo", url: "https://github.com/davidsonfellipe/awesome-wpo", category: "web", description: "awesome front-end development curated list" },
    { name: "Web Tools", owner: "lvwzhen", repo: "tools", url: "https://github.com/lvwzhen/tools", category: "web", description: "awesome front-end development curated list" },
    { name: "CSS", owner: "awesome-css-group", repo: "awesome-css", url: "https://github.com/awesome-css-group/awesome-css", category: "web", description: "awesome front-end development curated list" },
    { name: "Critical-Path Tools", owner: "addyosmani", repo: "critical-path-css-tools", url: "https://github.com/addyosmani/critical-path-css-tools", category: "web", description: "awesome front-end development curated list" },
    { name: "Flask", owner: "mjhea0", repo: "awesome-flask", url: "https://github.com/mjhea0/awesome-flask", category: "dev-ops", description: "awesome back-end development curated list" },
    { name: "Docker", owner: "veggiemonk", repo: "awesome-docker", url: "https://github.com/veggiemonk/awesome-docker", category: "dev-ops", description: "awesome back-end development curated list" },
    { name: "Vagrant", owner: "iJackUA", repo: "awesome-vagrant", url: "https://github.com/iJackUA/awesome-vagrant", category: "dev-ops", description: "awesome back-end development curated list" },
    { name: "Pyramid", owner: "uralbash", repo: "awesome-pyramid", url: "https://github.com/uralbash/awesome-pyramid", category: "dev-ops", description: "awesome back-end development curated list" },
    { name: "Play1 Framework", owner: "PerfectCarl", repo: "awesome-play1", url: "https://github.com/PerfectCarl/awesome-play1", category: "dev-ops", description: "awesome back-end development curated list" },
    { name: "University Courses", owner: "prakhar1989", repo: "awesome-courses", url: "https://github.com/prakhar1989/awesome-courses", category: "education", description: "awesome computer science curated list" },
    { name: "Data Science", owner: "academic", repo: "awesome-datascience", url: "https://github.com/academic/awesome-datascience", category: "education", description: "awesome computer science curated list" },
    { name: "Tutorials", owner: "siboehm", repo: "awesome-learn-datascience", url: "https://github.com/siboehm/awesome-learn-datascience", category: "education", description: "awesome computer science curated list" },
    { name: "Machine Learning", owner: "josephmisiti", repo: "awesome-machine-learning", url: "https://github.com/josephmisiti/awesome-machine-learning", category: "education", description: "awesome computer science curated list" },
    { name: "Tutorials", owner: "ujjwalkarn", repo: "Machine-Learning-Tutorials", url: "https://github.com/ujjwalkarn/Machine-Learning-Tutorials", category: "education", description: "awesome computer science curated list" },
    { name: "Big Data", owner: "0xnr", repo: "awesome-bigdata", url: "https://github.com/0xnr/awesome-bigdata", category: "database", description: "awesome big data curated list" },
    { name: "Public Datasets", owner: "awesomedata", repo: "awesome-public-datasets", url: "https://github.com/awesomedata/awesome-public-datasets", category: "database", description: "awesome big data curated list" },
    { name: "Hadoop", owner: "youngwookim", repo: "awesome-hadoop", url: "https://github.com/youngwookim/awesome-hadoop", category: "database", description: "awesome big data curated list" },
    { name: "Data Engineering", owner: "igorbarinov", repo: "awesome-data-engineering", url: "https://github.com/igorbarinov/awesome-data-engineering", category: "database", description: "awesome big data curated list" },
    { name: "Streaming", owner: "manuzhang", repo: "awesome-streaming", url: "https://github.com/manuzhang/awesome-streaming", category: "database", description: "awesome big data curated list" },
    { name: "Papers We Love", owner: "papers-we-love", repo: "papers-we-love", url: "https://github.com/papers-we-love/papers-we-love", category: "education", description: "awesome theory curated list" },
    { name: "Talks", owner: "JanVanRyswyck", repo: "awesome-talks", url: "https://github.com/JanVanRyswyck/awesome-talks", category: "education", description: "awesome theory curated list" },
    { name: "Algorithms", owner: "tayllan", repo: "awesome-algorithms", url: "https://github.com/tayllan/awesome-algorithms", category: "education", description: "awesome theory curated list" },
    { name: "Education", owner: "gaerae", repo: "awesome-algorithms-education", url: "https://github.com/gaerae/awesome-algorithms-education", category: "education", description: "awesome theory curated list" },
    { name: "Algorithm Visualizations", owner: "enjalot", repo: "algovis", url: "https://github.com/enjalot/algovis", category: "education", description: "awesome theory curated list" },
    { name: "Free Programming Books", owner: "EbookFoundation", repo: "free-programming-books", url: "https://github.com/EbookFoundation/free-programming-books", category: "education", description: "awesome books curated list" },
    { name: "Go Books", owner: "dariubs", repo: "GoBooks", url: "https://github.com/dariubs/GoBooks", category: "education", description: "awesome books curated list" },
    { name: "R Books", owner: "RomanTsegelskyi", repo: "rbooks", url: "https://github.com/RomanTsegelskyi/rbooks", category: "education", description: "awesome books curated list" },
    { name: "Mind Expanding Books", owner: "hackerkid", repo: "Mind-Expanding-Books", url: "https://github.com/hackerkid/Mind-Expanding-Books", category: "education", description: "awesome books curated list" },
    { name: "Book Authoring", owner: "TalAter", repo: "awesome-book-authoring", url: "https://github.com/TalAter/awesome-book-authoring", category: "education", description: "awesome books curated list" },
    { name: "Sublime Text", owner: "dreikanter", repo: "sublime-bookmarks", url: "https://github.com/dreikanter/sublime-bookmarks", category: "dev-tools", description: "awesome editors curated list" },
    { name: "Vim", owner: "mhinz", repo: "vim-galore", url: "https://github.com/mhinz/vim-galore", category: "dev-tools", description: "awesome editors curated list" },
    { name: "Neovim", owner: "rockerBOO", repo: "awesome-neovim", url: "https://github.com/rockerBOO/awesome-neovim", category: "dev-tools", description: "awesome editors curated list" },
    { name: "Emacs", owner: "emacs-tw", repo: "awesome-emacs", url: "https://github.com/emacs-tw/awesome-emacs", category: "dev-tools", description: "awesome editors curated list" },
    { name: "Visual Studio Code", owner: "viatsko", repo: "awesome-vscode", url: "https://github.com/viatsko/awesome-vscode", category: "dev-tools", description: "awesome editors curated list" },
    { name: "Game Development", owner: "ellisonleao", repo: "magictools", url: "https://github.com/ellisonleao/magictools", category: "game", description: "awesome gaming curated list" },
    { name: "Game Talks", owner: "hzoo", repo: "awesome-gametalks", url: "https://github.com/hzoo/awesome-gametalks", category: "game", description: "awesome gaming curated list" },
    { name: "Godot", owner: "godotengine", repo: "awesome-godot", url: "https://github.com/godotengine/awesome-godot", category: "game", description: "awesome gaming curated list" },
    { name: "Open Source Games", owner: "michelpereira", repo: "awesome-open-source-games", url: "https://github.com/michelpereira/awesome-open-source-games", category: "game", description: "awesome gaming curated list" },
    { name: "Unity", owner: "RyanNielson", repo: "awesome-unity", url: "https://github.com/RyanNielson/awesome-unity", category: "game", description: "awesome gaming curated list" },
    { name: "Quick Look Plugins", owner: "sindresorhus", repo: "quick-look-plugins", url: "https://github.com/sindresorhus/quick-look-plugins", category: "dev-tools", description: "awesome development environment curated list" },
    { name: "Dev Env", owner: "jondot", repo: "awesome-devenv", url: "https://github.com/jondot/awesome-devenv", category: "dev-tools", description: "awesome development environment curated list" },
    { name: "Dotfiles", owner: "webpro", repo: "awesome-dotfiles", url: "https://github.com/webpro/awesome-dotfiles", category: "dev-tools", description: "awesome development environment curated list" },
    { name: "Shell", owner: "alebcay", repo: "awesome-shell", url: "https://github.com/alebcay/awesome-shell", category: "dev-tools", description: "awesome development environment curated list" },
    { name: "Fish", owner: "jorgebucaran", repo: "awsm.fish", url: "https://github.com/jorgebucaran/awsm.fish", category: "dev-tools", description: "awesome development environment curated list" },
    { name: "Science Fiction", owner: "sindresorhus", repo: "awesome-scifi", url: "https://github.com/sindresorhus/awesome-scifi", category: "utility", description: "awesome entertainment curated list" },
    { name: "Fantasy", owner: "RichardLitt", repo: "awesome-fantasy", url: "https://github.com/RichardLitt/awesome-fantasy", category: "utility", description: "awesome entertainment curated list" },
    { name: "Podcasts", owner: "ayr-ton", repo: "awesome-geek-podcasts", url: "https://github.com/ayr-ton/awesome-geek-podcasts", category: "utility", description: "awesome entertainment curated list" },
    { name: "Email Newsletters", owner: "zudochkin", repo: "awesome-newsletters", url: "https://github.com/zudochkin/awesome-newsletters", category: "utility", description: "awesome entertainment curated list" },
    { name: "IT Quotes", owner: "victorlaerte", repo: "awesome-it-quotes", url: "https://github.com/victorlaerte/awesome-it-quotes", category: "utility", description: "awesome entertainment curated list" },
    { name: "Database", owner: "numetriclabz", repo: "awesome-db", url: "https://github.com/numetriclabz/awesome-db", category: "database", description: "awesome databases curated list" },
    { name: "MySQL", owner: "shlomi-noach", repo: "awesome-mysql", url: "https://github.com/shlomi-noach/awesome-mysql", category: "database", description: "awesome databases curated list" },
    { name: "SQLAlchemy", owner: "dahlia", repo: "awesome-sqlalchemy", url: "https://github.com/dahlia/awesome-sqlalchemy", category: "database", description: "awesome databases curated list" },
    { name: "InfluxDB", owner: "mark-rushakoff", repo: "awesome-influxdb", url: "https://github.com/mark-rushakoff/awesome-influxdb", category: "database", description: "awesome databases curated list" },
    { name: "Neo4j", owner: "neueda", repo: "awesome-neo4j", url: "https://github.com/neueda/awesome-neo4j", category: "database", description: "awesome databases curated list" },
    { name: "Fonts", owner: "brabadu", repo: "awesome-fonts", url: "https://github.com/brabadu/awesome-fonts", category: "media", description: "awesome media curated list" },
    { name: "Codeface", owner: "chrissimpkins", repo: "codeface", url: "https://github.com/chrissimpkins/codeface", category: "media", description: "awesome media curated list" },
    { name: "Stock Resources", owner: "neutraltone", repo: "awesome-stock-resources", url: "https://github.com/neutraltone/awesome-stock-resources", category: "media", description: "awesome media curated list" },
    { name: "GIF", owner: "davisonio", repo: "awesome-gif", url: "https://github.com/davisonio/awesome-gif", category: "media", description: "awesome media curated list" },
    { name: "Music", owner: "ciconia", repo: "awesome-music", url: "https://github.com/ciconia/awesome-music", category: "media", description: "awesome media curated list" },
    { name: "CLI Workshoppers", owner: "therebelrobot", repo: "awesome-workshopper", url: "https://github.com/therebelrobot/awesome-workshopper", category: "education", description: "awesome learn curated list" },
    { name: "Learn to Program", owner: "karlhorky", repo: "learn-to-program", url: "https://github.com/karlhorky/learn-to-program", category: "education", description: "awesome learn curated list" },
    { name: "Speaking", owner: "matteofigus", repo: "awesome-speaking", url: "https://github.com/matteofigus/awesome-speaking", category: "education", description: "awesome learn curated list" },
    { name: "Tech Videos", owner: "lucasviola", repo: "awesome-tech-videos", url: "https://github.com/lucasviola/awesome-tech-videos", category: "education", description: "awesome learn curated list" },
    { name: "Computer History", owner: "watson", repo: "awesome-computer-history", url: "https://github.com/watson/awesome-computer-history", category: "education", description: "awesome learn curated list" },
    { name: "Application Security", owner: "paragonie", repo: "awesome-appsec", url: "https://github.com/paragonie/awesome-appsec", category: "security", description: "awesome security curated list" },
    { name: "Security", owner: "sbilly", repo: "awesome-security", url: "https://github.com/sbilly/awesome-security", category: "security", description: "awesome security curated list" },
    { name: "CTF", owner: "apsdehal", repo: "awesome-ctf", url: "https://github.com/apsdehal/awesome-ctf", category: "security", description: "awesome security curated list" },
    { name: "Cyber Security University", owner: "brootware", repo: "awesome-cyber-security-university", url: "https://github.com/brootware/awesome-cyber-security-university", category: "security", description: "awesome security curated list" },
    { name: "Malware Analysis", owner: "rshipp", repo: "awesome-malware-analysis", url: "https://github.com/rshipp/awesome-malware-analysis", category: "security", description: "awesome security curated list" },
    { name: "Umbraco", owner: "umbraco-community", repo: "awesome-umbraco", url: "https://github.com/umbraco-community/awesome-umbraco", category: "web", description: "awesome content management systems curated list" },
    { name: "Refinery CMS", owner: "refinerycms-contrib", repo: "awesome-refinerycms", url: "https://github.com/refinerycms-contrib/awesome-refinerycms", category: "web", description: "awesome content management systems curated list" },
    { name: "Wagtail", owner: "springload", repo: "awesome-wagtail", url: "https://github.com/springload/awesome-wagtail", category: "web", description: "awesome content management systems curated list" },
    { name: "Textpattern", owner: "drmonkeyninja", repo: "awesome-textpattern", url: "https://github.com/drmonkeyninja/awesome-textpattern", category: "web", description: "awesome content management systems curated list" },
    { name: "Drupal", owner: "nirgn975", repo: "awesome-drupal", url: "https://github.com/nirgn975/awesome-drupal", category: "web", description: "awesome content management systems curated list" },
    { name: "Robotics", owner: "Kiloreux", repo: "awesome-robotics", url: "https://github.com/Kiloreux/awesome-robotics", category: "system-tools", description: "awesome hardware curated list" },
    { name: "Internet of Things", owner: "HQarroum", repo: "awesome-iot", url: "https://github.com/HQarroum/awesome-iot", category: "system-tools", description: "awesome hardware curated list" },
    { name: "Electronics", owner: "kitspace", repo: "awesome-electronics", url: "https://github.com/kitspace/awesome-electronics", category: "system-tools", description: "awesome hardware curated list" },
    { name: "Bluetooth Beacons", owner: "rabschi", repo: "awesome-beacon", url: "https://github.com/rabschi/awesome-beacon", category: "system-tools", description: "awesome hardware curated list" },
    { name: "Electric Guitar Specifications", owner: "gitfrage", repo: "guitarspecs", url: "https://github.com/gitfrage/guitarspecs", category: "system-tools", description: "awesome hardware curated list" },
    { name: "Open Companies", owner: "opencompany", repo: "awesome-open-company", url: "https://github.com/opencompany/awesome-open-company", category: "office", description: "awesome business curated list" },
    { name: "Places to Post Your Startup", owner: "mmccaff", repo: "PlacesToPostYourStartup", url: "https://github.com/mmccaff/PlacesToPostYourStartup", category: "office", description: "awesome business curated list" },
    { name: "OKR Methodology", owner: "domenicosolazzo", repo: "awesome-okr", url: "https://github.com/domenicosolazzo/awesome-okr", category: "office", description: "awesome business curated list" },
    { name: "Indie", owner: "mezod", repo: "awesome-indie", url: "https://github.com/mezod/awesome-indie", category: "office", description: "awesome business curated list" },
    { name: "Tools of the Trade", owner: "cjbarber", repo: "ToolsOfTheTrade", url: "https://github.com/cjbarber/ToolsOfTheTrade", category: "office", description: "awesome business curated list" },
    { name: "Slack", owner: "matiassingers", repo: "awesome-slack", url: "https://github.com/matiassingers/awesome-slack", category: "office", description: "awesome work curated list" },
    { name: "Communities", owner: "filipelinhares", repo: "awesome-slack", url: "https://github.com/filipelinhares/awesome-slack", category: "office", description: "awesome work curated list" },
    { name: "Remote Jobs", owner: "lukasz-madon", repo: "awesome-remote-job", url: "https://github.com/lukasz-madon/awesome-remote-job", category: "office", description: "awesome work curated list" },
    { name: "Productivity", owner: "jyguyomarch", repo: "awesome-productivity", url: "https://github.com/jyguyomarch/awesome-productivity", category: "office", description: "awesome work curated list" },
    { name: "Niche Job Boards", owner: "tramcar", repo: "awesome-job-boards", url: "https://github.com/tramcar/awesome-job-boards", category: "office", description: "awesome work curated list" },
    { name: "Software-Defined Networking", owner: "sdnds-tw", repo: "awesome-sdn", url: "https://github.com/sdnds-tw/awesome-sdn", category: "utility", description: "awesome networking curated list" },
    { name: "PCAPTools", owner: "caesar0301", repo: "awesome-pcaptools", url: "https://github.com/caesar0301/awesome-pcaptools", category: "utility", description: "awesome networking curated list" },
    { name: "Real-Time Communications", owner: "rtckit", repo: "awesome-rtc", url: "https://github.com/rtckit/awesome-rtc", category: "utility", description: "awesome networking curated list" },
    { name: "SNMP", owner: "eozer", repo: "awesome-snmp", url: "https://github.com/eozer/awesome-snmp", category: "utility", description: "awesome networking curated list" },
    { name: "Scapy", owner: "secdev", repo: "awesome-scapy", url: "https://github.com/secdev/awesome-scapy", category: "utility", description: "awesome networking curated list" },
    { name: "Bitcoin", owner: "igorbarinov", repo: "awesome-bitcoin", url: "https://github.com/igorbarinov/awesome-bitcoin", category: "network", description: "awesome decentralized systems curated list" },
    { name: "Ripple", owner: "vhpoet", repo: "awesome-ripple", url: "https://github.com/vhpoet/awesome-ripple", category: "network", description: "awesome decentralized systems curated list" },
    { name: "Non-Financial Blockchain", owner: "machinomy", repo: "awesome-non-financial-blockchain", url: "https://github.com/machinomy/awesome-non-financial-blockchain", category: "network", description: "awesome decentralized systems curated list" },
    { name: "Mastodon", owner: "hyperupcall", repo: "awesome-mastodon", url: "https://github.com/hyperupcall/awesome-mastodon", category: "network", description: "awesome decentralized systems curated list" },
    { name: "Ethereum", owner: "ttumiel", repo: "Awesome-Ethereum", url: "https://github.com/ttumiel/Awesome-Ethereum", category: "network", description: "awesome decentralized systems curated list" },
    { name: "Biomedical Information Extraction", owner: "caufieldjh", repo: "awesome-bioie", url: "https://github.com/caufieldjh/awesome-bioie", category: "utility", description: "awesome health and social science curated list" },
    { name: "Computational Neuroscience", owner: "eselkin", repo: "awesome-computational-neuroscience", url: "https://github.com/eselkin/awesome-computational-neuroscience", category: "utility", description: "awesome health and social science curated list" },
    { name: "Diversity", owner: "folkswhocode", repo: "awesome-diversity", url: "https://github.com/folkswhocode/awesome-diversity", category: "utility", description: "awesome health and social science curated list" },
    { name: "Digital History", owner: "maehr", repo: "awesome-digital-history", url: "https://github.com/maehr/awesome-digital-history", category: "utility", description: "awesome health and social science curated list" },
    { name: "Empathy in Engineering", owner: "KimberlyMunoz", repo: "empathy-in-engineering", url: "https://github.com/KimberlyMunoz/empathy-in-engineering", category: "utility", description: "awesome health and social science curated list" },
    { name: "Creative Tech Events", owner: "danvoyce", repo: "awesome-creative-tech-events", url: "https://github.com/danvoyce/awesome-creative-tech-events", category: "communication", description: "awesome events curated list" },
    { name: "Events in Italy", owner: "ildoc", repo: "awesome-italy-events", url: "https://github.com/ildoc/awesome-italy-events", category: "communication", description: "awesome events curated list" },
    { name: "Events in the Netherlands", owner: "awkward", repo: "awesome-netherlands-events", url: "https://github.com/awkward/awesome-netherlands-events", category: "communication", description: "awesome events curated list" },
    { name: "Testing", owner: "TheJambo", repo: "awesome-testing", url: "https://github.com/TheJambo/awesome-testing", category: "dev-tools", description: "awesome testing curated list" },
    { name: "Visual Regression Testing", owner: "mojoaxel", repo: "awesome-regression-testing", url: "https://github.com/mojoaxel/awesome-regression-testing", category: "dev-tools", description: "awesome testing curated list" },
    { name: "Selenium", owner: "christian-bromann", repo: "awesome-selenium", url: "https://github.com/christian-bromann/awesome-selenium", category: "dev-tools", description: "awesome testing curated list" },
    { name: "Appium", owner: "SrinivasanTarget", repo: "awesome-appium", url: "https://github.com/SrinivasanTarget/awesome-appium", category: "dev-tools", description: "awesome testing curated list" },
    { name: "TAP", owner: "sindresorhus", repo: "awesome-tap", url: "https://github.com/sindresorhus/awesome-tap", category: "dev-tools", description: "awesome testing curated list" },
    { name: "Scientific Writing", owner: "writing-resources", repo: "awesome-scientific-writing", url: "https://github.com/writing-resources/awesome-scientific-writing", category: "utility", description: "awesome miscellaneous curated list" },
    { name: "JSON", owner: "burningtree", repo: "awesome-json", url: "https://github.com/burningtree/awesome-json", category: "utility", description: "awesome miscellaneous curated list" },
    { name: "GeoJSON", owner: "tmcw", repo: "awesome-geojson", url: "https://github.com/tmcw/awesome-geojson", category: "utility", description: "awesome miscellaneous curated list" },
    { name: "CSV", owner: "secretGeek", repo: "awesomeCSV", url: "https://github.com/secretGeek/awesomeCSV", category: "utility", description: "awesome miscellaneous curated list" },
    { name: "Discounts for Student Developers", owner: "AchoArnold", repo: "discount-for-student-dev", url: "https://github.com/AchoArnold/discount-for-student-dev", category: "utility", description: "awesome miscellaneous curated list" },
    { name: "All Awesome Lists", owner: "topics", repo: "awesome", url: "https://github.com/topics/awesome", category: "utility", description: "awesome related curated list" },
    { name: "StumbleUponAwesome", owner: "basharovV", repo: "StumbleUponAwesome", url: "https://github.com/basharovV/StumbleUponAwesome", category: "utility", description: "awesome related curated list" },
    { name: "Awesome CLI", owner: "umutphp", repo: "awesome-cli", url: "https://github.com/umutphp/awesome-cli", category: "utility", description: "awesome related curated list" },
];